### PR TITLE
StartPoint, EndPoint fix on props/types after last version (2.4.0)

### PR DESCRIPTION
**Pull request by Lube**
As the title says simple fix, please review and release asap.

### CODE REVIEW

**Comment by MrLoh** [comment]
@Lube I think there is a misunderstanding. 2.4 does not change the interface on the react side of things. Just keep using `start` and `end` there.

**Comment by prerakd** [comment]
@MrLoh If we update react-native to 0.51, using start and end as a prop will lead to crash.
see #235

**Comment by MrLoh** [comment]
I don’t think so.

**Comment by prerakd** [comment]
@MrLo you are right!!! my bad!! Working fine after reinstalling app.

**Comment by MrLoh** [comment]
@Lube you should close this PR

**Comment by zhanghuiyun** [comment]
How to deal it

**Comment by MrLoh** [comment]
Just goon with life there’s nothing you have to do. If you update react native also update this package, don’t change your code.

**Comment by zhanghuiyun** [comment]
Thanks for your advice, but we can't upgrade. I have found a solution now. @MrLoh

**Comment by zhanghuiyun** [comment]
I am now implementing horizontal gradients through the rotation of the elements. @MrLoh

**Comment by MrLoh** [comment]
If you can upgrade React native (which causes the issue in the first place) you should also be able to update this library.

**Pull request closed without merging**
