### PR TITLE
rename start/end properties internally (React Native .51 compatibility)

### PR DESCRIPTION
**Pull request by koenpunt**
to prevent clash with RN Yoga properties

Same like some other PRs (#243, #242), but with the exception that I didn't change the public API, and so the upgrade is non-breaking.

### CODE REVIEW

**Comment by dannycochran** [comment]
Should probably update the typings to for "startPoint" and "endPoint"

**Comment by koenpunt** [comment]
Don’t think so, because the public api didn’t change.

**Comment by dannycochran** [comment]
Ah I see, the other PR does have breaking changes to the public API. My mistake, that's the one I had forked.

**Comment by sjmueller** [comment]
I have updated my original PR to support android.

**Comment by koenpunt** [comment]
Great, will close this then

**Pull request closed without merging**
