### PR TITLE
Rename start & end properties to fix conflict with RN 51

### PR DESCRIPTION
**Pull request by sjmueller**
A [recent commit in RN](https://github.com/facebook/react-native/commit/38b5506599b12d5c6ac3a2dd3f047ccf067cfc71#diff-cc240c1301db07911d48d3cfb9741423R272) added start/end properties to RCTViewManager.
Because LinearGradient inherits from this class and has properties of
the same name, RN gets mixed up and tries to convert to a `YGValue`
instead of `CGPoint`, which results in the exception:

```
Error setting property 'start' of BVLinearGradient with tag #18: JSON
value '{
    x = 0;
    y = 0;
}' of type NSMutableDictionary cannot be converted to a YGValue.
```

This PR renames the values to avoid conflict, but keeps the JavaScript component API the same, thus preventing a breaking change.

### CODE REVIEW

**Comment by Psyycker** [comment]
Please accept-it, I need it !

**Comment by MichaelDanielTom** [comment]
I just did the same thing for Android here FYI:
https://github.com/react-native-community/react-native-linear-gradient/pull/242

**Comment by bilalsyed001** [comment]
#243

**Comment by imekinox** [comment]
+1 Please I need it too.

**Comment by sjmueller** [comment]
Hey folks, I have updated this PR to support android as well. I know there have been several follow up PRs since my original submission and it's gotten a bit confusing -- hopefully this now takes care of everything and we can get it merged.

**Comment by afilp** [comment]
Can you please merge this? Thanks!

**Comment by adamski** [comment]
Also need this! Just updated to RN 0.51

**Comment by matthargett** [comment]
just FYI for @kevinvangelder : you'll need to update #145 once this is merged before that PR can be merged.

**Comment by GantMan** [comment]
party2

**Comment by bmovement** [comment]
Trying to `yarn upgrade` this to no avail... should there have been an accompanying version bump, or am I doing something wrong? 😅

**Comment by hwangjr** [comment]
But, We also need a new release for this pr.

**Comment by adamski** [comment]
For the impatient, just add the git url to your package.json:
```json
"react-native-linear-gradient": "git+https://github.com/react-native-community/react-native-linear-gradient.git",
```

**Comment by GantMan** [comment]
Released 2.4.0

**Comment by GantMan** [comment]
:(  any idea on the fix?

**Comment by abeddow91** [comment]
also getting the same issue here with 

└─ react-native-linear-gradient@2.5.2
└─ react-native: 0.57.7

**Pull request merged**
