### PR TITLE
Changed start and end props for android to be compatible with RN 0.51+

### PR DESCRIPTION
**Pull request by MichaelDanielTom**

### CODE REVIEW

**Comment by bilalsyed001** [comment]
#243

**Comment by ZooTopiaGG** [comment]
Have you solved it? and how to change end and start props for android

**Comment by sjmueller** [comment]
I have updated my original PR to support android without breaking the existing API, so this one can likely be closed.

**Comment by sibelius** [comment]
fixed here https://github.com/react-native-community/react-native-linear-gradient/pull/235

**Pull request closed without merging**
