### PR TITLE
React Native Windows Support

### PR DESCRIPTION
**Pull request by kevinvangelder**
UWP (Windows 8/10) & WPF (Windows 7)

### CODE REVIEW

**Comment by sibelius** [comment]
@kevinvangelder can u rebase? I think we can merge this

**Comment by sibelius** [comment]
anybody want's to test and finish this?

**Comment by kevinvangelder** [comment]
Sorry for the delay, and thanks for the reminder. This package is in use in BlueJeans' production video conferencing app for Windows 7/8/10. The implementation differs slightly from the iOS implementation (as discussed in #134), but otherwise should work the same.

**Comment by sibelius** [comment]
Tks, let’s make this work

**Pull request merged**
