### PR TITLE
little improvement over too many "def"

### PR DESCRIPTION
**Pull request by yeomann**
just a little improved version rather then many explicit def for each value.
Also added `26.0.3` for buildToolsVersion rather than `26.0.1`.

### CODE REVIEW

**Comment by radex** [comment]
@rozPierog got time to take a look at this? You saw a lot of android RN libraries gradle files…

**Comment by yeomann** [comment]
oh i even didn't remember when i send this pull req ;p i will check the conflicts soon 😃  @rozPierog thanks

**Comment by radex** [comment]
@yeomann hey, can you resolve conflicts and verify this still works? :)

**Comment by yeomann** [comment]
ok sorry forgot again because of job changing etc. i'll check soon @radex

**Comment by friederbluemle** [comment]
Thanks @yeomann for your PR - It is the right approach! A more recent version was part of the already merged PR #435 - Closing this.

**Pull request closed without merging**
