### PR TITLE
Added support for setting an angle for the gradient

### PR DESCRIPTION
**Pull request by danielgindi**
This builds on an earlier PR for dithering on iOS (#215)

### CODE REVIEW

**Comment by jamesqo** [comment]
@sibelius @GantMan Is this library no longer accepting any new features? The latest commits all seem to be bugfixes/typo corrections.

**Comment by danielgindi** [comment]
Rebased on latest `master`

**Comment by sibelius** [comment]
@k0nserv can u review this?

**Comment by k0nserv** [comment]
Wouldn't it be nicer to maintain and use if we instead added the angle logic in JS? e.g. something like

```javascript
import LinearGradient, { createAngleGradient } from 'react-native-linear-gradient';

export default () => <LinearGradient {...createAngleGradient(45, { x: 0.5, y: 0.5 })} />
```

Or maybe via a `HOC` or something? Keeping the native code dumb seems like a good idea because anthing done on the native side has to be done twice

**Comment by danielgindi** [comment]
Nope. The problem in the JS is that you only know the dimensions of the view *after* it has already been laid out for the first time, which create bugs when viewing the layer.
Take for example the case of an angled gradient layer as the background of a screen inside a `react-native-navigation`.

**Comment by k0nserv** [comment]
> The purpose of this effect is to be able to create gradients like you create in photoshop: You have the start/end points, the angle, and it calculates where the gradient should actually begin while keeping that angle. When calculating an angle without considering the size of the view you get "weird" gradients, which do not start or end at the expected points, and do not even keep their angle as they get "stretched" to the size of the view. (You are basically calculating based on a 1.0x1.0 grid, and stretching to say 375x667)

From my research the issue with a square gradient upscaled to the size of the view was present with the previous implementation based on `CAGradientLayer`, but the new implementation shouldn't suffer from this problem. In my tests the new implementation correctly matches gradient generated in Sketch for non square views. From an API perspective I'd expect that you can either give an angle and a center or a start and end points. See https://github.com/react-native-community/react-native-linear-gradient/pull/215#issuecomment-397233816

**Comment by danielgindi** [comment]
Yes but the thing is we must calculate the new gradient points base on the angle + size.
The JS calculated angle produces different results. I tried that first...

**Comment by k0nserv** [comment]
Okay yeah that makes sense. Can we include some documentation for this usage and when you'd want to use it? It's still not quite clear to me

**Comment by danielgindi** [comment]
Yeah I'll try to find some time for it  soon

**Comment by danielgindi** [comment]
Added some docs

**Comment by danielgindi** [comment]
@k0nserv

**Comment by henrikra** [comment]
@danielgindi Also note that you have to update types on `index.d.ts`

**Comment by radex** [comment]
@danielgindi Hey, could you update the branch with the latest master and check if this still works (on both iOS and Android)? I can review the code and merge if looks good, but want to be sure that changes over the last couple of months won't interfere with your changes

**Comment by henrikra** [comment]
Could you also example image about this angled gradient either to this PR or to README? :)

**Comment by danielgindi** [comment]
@radex I've rebased on `master`, added TS definitions, and tested again. Works fine!

**Comment by danielgindi** [comment]
I'll try to make up something for this (also anyone who used gradients in Photoshop will understand what this is)
But I'm with a newborn baby, it will probably take some time. Could be a followup PR.

**Comment by radex** [comment]
Thanks @danielgindi

**Pull request merged**
