### PR TITLE
[TvOS] Add tvOS target

### PR DESCRIPTION
**Pull request by JulienKode**
Add a target to use it on tvOS

### CODE REVIEW

**Comment by grylance** [comment]
Nice one, would like to see this released.

**Comment by jeroentradecast** [comment]
I'd really like to have this released too.

**Comment by JulienKode** [comment]
@grylance  @jeroentradecast Yes we really need that 😊

**Comment by Kureev** [comment]
I can merge it in, but I can't release it 😒

**Comment by dgladkov** [comment]
Thank you for the PR and sorry for the long delay! Merged and released as version 2.3.0

**Comment by JulienKode** [comment]
@dgladkov Thank you 👍

**Pull request merged**
