### PR TITLE
bump Android libs

### PR DESCRIPTION
**Pull request by ralphpina**

### CODE REVIEW

**Comment by vinagrito** [comment]
@dgladkov would this make any sense?

**Comment by k0nserv** [comment]
@dgladkov any chance this can be merged?

**Comment by uqmessias** [comment]
@nickhudkins and @dgladkov, is there any chance this PR be merged soon?

**Comment by GantMan** [comment]
Looks good, as mentioned in #228

**Comment by uqmessias** [comment]
@faifai21, Do I have to do any additional steps to use the library with [this new config](https://github.com/react-native-community/react-native-linear-gradient/pull/163/commits/8dab866d8cbe040bdf91d6303edbfedc22409450#diff-7ae5a9093507568eabbf35c3b0665732R30)? If so, how can I proceed?

**Pull request merged**
