### PR TITLE
BREAKING: Update for RN@0.40.0, new header paths

### PR DESCRIPTION
**Pull request by rh389**
React native is planning a breaking change to header paths in 0.40.0, this PR is in preparation for that. Also updated the example to 0.40.0-rc.4 (using the tag as it's currently unpublished).

### CODE REVIEW

**Comment by rh389** [comment]
I accidentally crossed with @ptmt's https://github.com/react-native-community/react-native-linear-gradient/pull/131 here (sorry @ptmt). I'm pretty sure angle brackets are preferred though?

**Comment by ptmt** [comment]
Thanks @rh389! Your update looks more solid and it fixes more things. Let's forget about mine.

**Comment by binchik** [comment]
@dgladkov Hi, can you please merge this commit? 0.40 is out already.

**Comment by dsernst** [comment]
Please merge 😄 `react-native-linear-gradient` fails build on latest version of RN until these changes are made

**Comment by rh389** [comment]
This PR could use an update I think - I'm on it.

**Comment by rh389** [comment]
Ok - I've now rebased and built the example against 0.40.0 (rather than an rc). I've also put in a major version bump to 2.0.0, since this breaks compatibility with RN <= 0.39

**Comment by aforty** [comment]
Please merge this asap.

**Comment by binchik** [comment]
@rh389 Hi, can you please list the steps to make it work? 

I've installed the package using the `react-native-linear-gradient@rh389/react-native-linear-gradient#rn040`, unlinked and linked it back. However, Xcode shows me the following output:

```
fatal error: 'React/RCTView.h' file not found
#import <React/RCTView.h>
```

**Comment by adrienbataille** [comment]
@rh389 Will you release soonly a new version or should we have to use `npm install --save react-native-linear-gradient@rh389/react-native-linear-gradient#rn040` for a while with RN 0.40?!

**Comment by rh389** [comment]
@adrienbataille I'll keep my fork alive but it's up to this package's maintainers to merge and release - nothing I can do.

cc @brentvatne @dgladkov @nickhudkins

**Comment by adrienbataille** [comment]
@rh389 Thanks

@brentvatne @dgladkov @nickhudkins Same question, will you release soonly a new version or should we have to use the @rh389 fork for a while with RN 0.40?!

**Comment by rh389** [comment]
I should say I haven't tested this in all situations - is anyone using `react-native-linear-gradient` as a Pod, and/or from swift?

**Comment by dgladkov** [comment]
Thanks for your contribution and sorry for the delayed response. Didn't have a chance to test RN 0.40.x yet, however folks above seem to have no issues with the change, so I'm shipping it as is. Please let me know if you encounter any issues.

**Pull request merged**
