### PR TITLE
Replace PropTypes from react with form prop-types package

### PR DESCRIPTION
**Pull request by gitim**
see https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes

### CODE REVIEW

**Comment by jayarprado** [comment]
Hope this gets merged soon. 👍

**Comment by gitim** [comment]
@GantMan thanks for approving the pr, could you publish a new version with that fix?

**Comment by Ignigena** [comment]
Causing builds to fail when using latest RN, would love to see an NPM bump!

**Comment by GantMan** [comment]
If it's still not published by next Wednesday, I'll do it!

**Comment by GantMan** [comment]
@gitim - I'm having trouble testing this again bc I'm running into this issue with node-gyp

https://github.com/brianmcd/contextify/issues/205

**Comment by gitim** [comment]
@GantMan it caused by jest-cli dependency. Is it really used? I think we can just delete it from deps.

**Comment by gitim** [comment]
I created a pr that remove jest-cli https://github.com/react-native-community/react-native-linear-gradient/pull/192

**Comment by GantMan** [comment]
Released 2.1

**Comment by gitim** [comment]
> Released 2.1

Cool, thanks! But looks like you forgot to update a version in package.json in master.

**Pull request merged**
