### PR TITLE
Updated gradle version to 3.1.2

### PR DESCRIPTION
**Pull request by default911**
Could not find com.android.tools:common:25.3.3 fix
See Issue#375 on https://github.com/react-native-community/react-native-linear-gradient/issues/375

### CODE REVIEW

**Comment by radex** [comment]
I need more information before I can do this.

See this thread: https://github.com/react-native-community/react-native-linear-gradient/pull/362

There was another thing about upgrading gradle to v3, but the problem was that this would work in RN 0.57+, but would not work in RN 0.56 that a lot of people still use.

If someone can verify and confirm that this fix doesn't break support for RN 0.56, I can merge.

/cc @default911 @bitcrumb @fschindler @rozpierog

**Comment by default911** [comment]
@radex I will check and update shortly

**Comment by bitcrumb** [comment]
Could this be related with this?
https://issuetracker.google.com/issues/120759347

**Comment by default911** [comment]
Yes. This is also related to the same issue. Should we hold on this PR until Google fixes above issue? My question is why aren't you guys upgrading Gradle version when a lot of other react native libraries have done so already?

**Comment by default911** [comment]
@radex I guess we should wait for Google to fix the issue instead. I'm not sure of merging this right now.

**Pull request closed without merging**
